### ISSUE TITLE
doesnt work in editing model

### ISSUE THREAD

**Issue by Feiiish** [jillalberts/privacy-glasses#6] opened 2022-03-17 08:26 UTC
Thanks you for this awesome plugin. but it works in reading model, but not in editing model. i use the default theme.

**Comment by jillalberts** [comment] 2022-03-17 15:49
Hello, this is a duplicate of Issue #5 

I am no longer working on this project and am unlikely to return to it; it is pretty much abandoned. But the code is open-source and distributed under the MIT license, so anyone who wants to fix or improve anything is free to fork the project and do pretty much whatever they'd like.

**Comment by Feiiish** [comment] 2022-03-18 04:33
thanks for your help

**Closed** 2022-04-18 23:47 UTC
